# Copyright 2026, EOX (https://eox.at) and Versioneer (https://versioneer.at)
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Secret
metadata:
  name: lakefs-blockstore
  namespace: lakefs
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: ${LAKEFS_BLOCKSTORE_ACCESS_KEY_ID}
  AWS_SECRET_ACCESS_KEY: ${LAKEFS_BLOCKSTORE_SECRET_ACCESS_KEY}
