# Copyright 2025, EOX (https://eox.at) and Versioneer (https://versioneer.at)
# SPDX-License-Identifier: Apache-2.0

name: Publish Bases to GHCR

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

permissions:
  contents: read
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      IMAGE: ghcr.io/${{ github.repository_owner }}/bases
      OWNER: ${{ github.repository_owner }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Install Flux CLI
        run: |
          set -eux
          curl -s https://fluxcd.io/install.sh | sudo bash
          flux --version

      - name: Authenticate to GHCR
        env:
          CR_PAT: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "$CR_PAT" | docker login ghcr.io -u "${OWNER}" --password-stdin

      - name: Make script executable
        run: chmod +x ./publish-bases.sh

      - name: Publish changed bases via Flux OCI
        env:
          IMAGE: ${{ env.IMAGE }}
          OWNER: ${{ env.OWNER }}
        run: ./publish-bases.sh
